image: docker:20.10.16-dind

variables:
    DOCKER_HOST: tcp://docker:2375
    #
    # This instructs Docker not to start over TLS.
    DOCKER_TLS_CERTDIR: ""
stages:
  - build

# test:
#   stage: test
#   image: golang:latest
#   tags:
#     - test
#   script:
#     - go fmt $(go list ./... | grep -v /vendor/)
#     - go vet $(go list ./... | grep -v /vendor/)
#     - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  tags:
    - build
  services:
    - docker:dind
  script:
    - docker build -t recipe-api .
    - docker run recipe-api

