image: docker:20.10.16-dind

stages:
  - test
  - build

test:
  stage: test
  image: golang:latest
  tags:
    - test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  tags:
    - build
  services:
    - docker:20.10.16-dind
  script:
    - docker build -t recipe-api .
    - docker run recipe-api

